Repository dalbitresb12/easyleasing-app, pull requests merged in 2022-11, with the labels that each got.

#1 chore: project setup
  .eslintrc.json
  .prettierrc.json
  .vscode/settings.json
  LICENSE
  README.md
  next.config.js
  package.json
  public/_redirects
  src/components/card.tsx
  src/components/layout.tsx
  src/components/material-icon.tsx
  src/css/base.css
  src/pages/_app.tsx
  src/pages/api/hello.ts
  src/pages/calculator.tsx
  src/pages/help.tsx
  src/pages/index.tsx
  src/pages/saved.tsx
  src/pages/settings/general.tsx
  src/pages/settings/index.tsx
  src/typings/svg.d.ts
  src/utils/redirect-page.tsx
  yarn.lock
Labels: enhancement

#2 chore: wrangler setup
  .gitignore
  .yarn/patches/wrangler-npm-2.3.0-fc5dd28b00.patch
  functions/api/index.ts
  functions/tsconfig.json
  package.json
  tsconfig.json
  wrangler.toml
  yarn.lock
Labels: chore

#3 chore(algorithm): setup algorithm script
  algorithm/index.mjs
  package.json
  yarn.lock
Labels: chore

#5 feat: Authentication and User Management
  .eslintignore
  .eslintrc.json
  .gitignore
  .prettierignore
  .stylelintignore
  .vscode/settings.json
  functions/api/_middleware.ts
  functions/api/auth/login.ts
  functions/api/auth/register.ts
  functions/api/auth/reset-password.ts
  functions/api/auth/send-reset-password.ts
  functions/api/auth/verify-email.ts
  functions/api/index.ts
  functions/api/users/me.ts
  functions/api/users/picture.ts
  functions/tsconfig.json
  functions/types/appcontext.ts
  functions/utils/bodyparser.ts
  functions/utils/postmark.ts
  next.config.js
  package.json
  public/_redirects
  public/undraw_authentication_re_svpt.svg
  public/undraw_forgot_password_re_hxwm.svg
  public/undraw_mail_sent_re_0ofv.svg
  public/undraw_server_down_s-4-lk.svg
  shared/api/types/auth/index.ts
  shared/api/types/auth/login.ts
  shared/api/types/auth/register.ts
  shared/api/types/auth/reset-password.ts
  shared/api/types/auth/send-reset-password.ts
  shared/api/types/auth/verify-email.ts
  shared/api/types/common/http-error.ts
  shared/api/types/common/index.ts
  shared/api/types/common/success-response.ts
  shared/api/types/index.ts
  shared/models/user.ts
  shared/utils/zod-errors.ts
  src/api/handlers/auth.ts
  src/api/handlers/index.ts
  src/api/handlers/users.ts
  src/api/keys/index.ts
  src/api/keys/users.ts
  src/components/form-button.tsx
  src/components/form-input.tsx
  src/components/layout.tsx
  src/pages/_app.tsx
  src/pages/auth/login.tsx
  src/pages/auth/register.tsx
  src/pages/auth/reset-password.tsx
  src/pages/auth/send-reset-password.tsx
  src/pages/auth/verify-email.tsx
  src/pages/index.tsx
  src/utils/http-client.ts
  src/utils/jwt-store.ts
  src/utils/query.ts
  src/utils/use-auth-guard.ts
  tsconfig.json
  wrangler.toml
  yarn.lock
Labels: enhancement, scope: auth, scope: api

#6 style: sorted imports with prettier plugin
  .prettierrc.json
  functions/api/_middleware.ts
  functions/api/auth/login.ts
  functions/api/auth/register.ts
  functions/api/auth/reset-password.ts
  functions/api/auth/send-reset-password.ts
  functions/api/auth/verify-email.ts
  functions/api/users/me.ts
  functions/api/users/picture.ts
  functions/utils/postmark.ts
  package.json
  shared/api/types/auth/login.ts
  src/api/handlers/auth.ts
  src/api/handlers/users.ts
  src/components/layout.tsx
  src/pages/_app.tsx
  src/pages/auth/login.tsx
  src/pages/auth/register.tsx
  src/pages/auth/reset-password.tsx
  src/pages/auth/send-reset-password.tsx
  src/pages/auth/verify-email.tsx
  src/utils/http-client.ts
  src/utils/use-auth-guard.ts
  yarn.lock
Labels: chore

#4 feat(algorithm): CLI implementation
  algorithm/index.mjs
  package.json
  yarn.lock
Labels: enhancement, scope: algorithm

#7 feat(ui): User Settings
  functions/api/auth/register.ts
  functions/api/auth/reset-password.ts
  functions/api/users/me.ts
  functions/api/users/picture.ts
  shared/models/user.ts
  src/api/handlers/users.ts
  src/components/circular-avatar.tsx
  src/components/form-input.tsx
  src/components/layout.tsx
  src/components/picture-input.tsx
  src/components/search-bar-layout.tsx
  src/components/settings-input.tsx
  src/components/settings-layout.tsx
  src/components/settings-page.tsx
  src/components/tab-bar.tsx
  src/pages/_app.tsx
  src/pages/settings/defaults.tsx
  src/pages/settings/general.tsx
  src/pages/settings/security.tsx
  src/utils/date-formatter.ts
  src/utils/http-client.ts
Labels: enhancement, scope: ui

#8 ci: update actions/checkout to v3
  .github/workflows/reviewdog.yml
Labels: ci

#9 style: fix algorithm.mjs with prettier
  algorithm/index.mjs
Labels: chore

#10 fix: Algorithm problems
  algorithm/index.mjs
Labels: bug, scope: algorithm

#13 refactor: Algorithm changes
  algorithm/index.mjs
  algorithm/initial-data.mjs
  algorithm/leasing-results.mjs
  algorithm/payment-calculations.mjs
  algorithm/profitability-indicator.mjs
  algorithm/rate-conversion.mjs
  algorithm/utils.mjs
  algorithm/validations.mjs
Labels: refactor

#12 feat(ui): Docs pages
  .github/workflows/reviewdog.yml
  .markdownlint.json
  .vscode/extensions.json
  .vscode/settings.json
  docs/index.md
  docs/page.md
  package.json
  public/single-earth-FP5tOXT6aMs-unsplash.jpg
  src/pages/help.tsx
  src/pages/help/[[...slug]].tsx
  src/utils/markdown.ts
  tailwind.config.js
  yarn.lock
Labels: documentation, enhancement

#11 feat: Calculator
  .eslintrc.json
  .vscode/settings.json
  functions/api/_middleware.ts
  functions/api/auth/login.ts
  functions/api/auth/register.ts
  functions/api/auth/reset-password.ts
  functions/api/auth/send-reset-password.ts
  functions/api/auth/verify-email.ts
  functions/api/leasings/[id].ts
  functions/api/leasings/index.ts
  functions/api/users/me.ts
  functions/tsconfig.json
  functions/types/appcontext.ts
  functions/utils/bodyparser.ts
  functions/utils/model-parser.ts
  functions/utils/params.ts
  functions/utils/postmark.ts
  functions/utils/urls.ts
  package.json
  shared/api/types/common/http-error.ts
  shared/api/types/common/paginated-response.ts
  shared/api/types/index.ts
  shared/api/types/leasings/index.ts
  shared/models/common.ts
  shared/models/leasing.ts
  shared/models/user.ts
  shared/utils/algorithm.ts
  shared/utils/numbers.ts
  shared/utils/strings.ts
  shared/utils/zod-errors.ts
  src/api/handlers/leasings.ts
  src/api/keys/index.ts
  src/api/keys/leasings.ts
  src/components/calculator-input.tsx
  src/components/form-button.tsx
  src/components/form-input.tsx
  src/components/layout.tsx
  src/components/listbox-input.tsx
  src/components/progress-bar.tsx
  src/components/progress-layout.tsx
  src/components/switch-input.tsx
  src/pages/calculator.tsx
  src/pages/calculator/basic.tsx
  src/pages/calculator/extra.tsx
  src/pages/leasings/details.tsx
  src/utils/http-client.ts
  src/utils/use-combined-refs.ts
  wrangler.toml
  yarn.lock
Labels: enhancement, scope: api, scope: ui

#16 docs: update docs titles and content
  docs/concepts.md
  docs/guide.md
  docs/index.md
Labels: documentation

#15 feat(ui): Leasing pages
  functions/api/leasings/[id].ts
  functions/api/leasings/index.ts
  package.json
  shared/api/types/leasings/index.ts
  shared/finance/initial-data.ts
  shared/finance/leasing-results.ts
  shared/finance/models/extra-cost.ts
  shared/finance/models/payment.ts
  shared/finance/payment-calculations.ts
  shared/finance/profitability-indicators.ts
  shared/finance/rate-conversion.ts
  shared/models/common.ts
  shared/models/leasing.ts
  shared/utils/algorithm.ts
  shared/utils/numbers.ts
  shared/utils/strings.ts
  src/components/divided-table.tsx
  src/components/form-input.tsx
  src/components/layout.tsx
  src/components/progress-bar.tsx
  src/pages/calculator/basic.tsx
  src/pages/calculator/extra.tsx
  src/pages/leasings/details.tsx
  src/pages/saved.tsx
  src/utils/use-combined-refs.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, scope: ui

#17 fix(http): query was using stale data when rendering details page
  src/pages/calculator/extra.tsx
Labels: bug

#18 feat(ui): grace periods selection
  shared/models/common.ts
  src/components/listbox-input.tsx
  src/components/progress-layout.tsx
  src/pages/calculator/basic.tsx
  src/pages/calculator/extra.tsx
  src/pages/calculator/periods.tsx
Labels: enhancement, scope: ui

#19 fix: nominal rate conversion
  shared/finance/initial-data.ts
Labels: bug, scope: algorithm

#20 feat(ui): create payment schedule page
  shared/utils/numbers.ts
  src/css/base.css
  src/pages/leasings/details.tsx
  src/pages/leasings/schedule.tsx
Labels: enhancement, scope: ui
